### ISSUE TITLE
Compatibility with Cordova 6.0.0, Cordova iOS 4.0.1 and Cordova Android 5.1.0 

### ISSUE THREAD

**Issue by krishnaff** [aporat/cordova-plugin-fetch#10]
Hello, 

This is an awesome plugin for cordova.
I'm trying to make it work in Meteor-cordova and it looks like there are compatibility issues.
https://github.com/meteor/meteor/issues/6356

Just wanted to understand if theres a way to fix this. Thanks!

More info:
In Xcode, build fails with this error:
`FetchPlugin.h`
`Cordova/CDVJSON.h file not found`

**Comment by posabsolute** [comment]
+1

**Comment by krishnaff** [comment]
https://github.com/christocracy/cordova-plugin-background-fetch/issues/28
Just commenting out `#import <Cordova/CDVJSON.h>` worked.

**Comment by braianj** [comment]
it's not working for me, any idea?

**Comment by ericgopak** [comment]
I had the same error, although I wasn't getting it previously and haven't performed any updates.

What worked for me was to cleanup both plugins and platforms directories:
`rm -rf platforms`
`rm -rf plugins`

Good luck!

(note: commenting out the line with `#import <Cordova/CDVJSON.h>` did not work for me, but even if it worked for you, I would encourage you to investigate deeper into the issue)
