### ISSUE TITLE
Android: "Content-Type": "application/json" does not work

### ISSUE THREAD

**Issue by krishnaff** [aporat/cordova-plugin-fetch#11]
Hello, 

The plugin works flawlessly on iOS. 
On Android though, I get an error that the Content-Type is not set as "application/json". 

I have explicitly set the headers as: 
`headers: { "Accept": "application/json", "Content-Type": "application/json" }`

Any idea why this is not working on Android? Have a near production app, so very critical I figure this out. 
Thanks!

**Comment by aporat** [comment]
Sorry, but I no longer actively using this plugin, as I'm mostly working with native tools these days. 

I'll love it if you can check it the issue and open a pull request to fix the issue.

**Comment by krishnaff** [comment]
@aporat Thanks for your response. 
I realised, Android only supports POST call. On iOS I could use all types of calls - post, get, put, delete.
I don't know the first thing about Android Java, so not sure how I can fix this. 

Is it because the plugin supports all the calls, but its not wired up in the Android plugin source file (FetchPlugin.java)? Any pointers would be really great.

**Comment by aporat** [comment]
the android plugin should support all http verbs. I think I've used `GET` requests on android and they worked fine. (but perhaps it worked because the api I used only accepted JSON).

Here's a code example I previously used:

```
 let req = {
        method  : GET,
        headers: {},
      };

    req.method = method;

      if (method === GET) {
        path += '?'+getAsUrlParams(params);
      } else {
        req.body = JSON.stringify(params);
      }
      req.headers['Content-Type'] = "application/json";
      req.headers['Accept'] = "application/json; charset=UTF-8";
      req.headers['User-Agent'] = APP_NAME + " (Browser; 1.0.0; Android)";

      //console.log(baseUrl + path);
     //  console.log(req);
      return window.cordovaFetch(baseUrl + path, req)
        .then((response) => {
          const responseJSON = JSON.parse(response.statusText);

          return responseJSON;
        })
        .catch((err) => {
          console.log(err);
        });
    };

  const getAsUrlParams = (params) => {
      const keys = _.keys(params).sort();
      let paramsArr = [];
      _.each(keys, (key) => {

        if (params[key] != null && params[key] != "") {

          if (typeof params[key] === 'string') {
            paramsArr.push(key + '=' + params[key]);
          } else {
            paramsArr.push(key + '=' + JSON.stringify(params[key]));
          }
        }
      });

      return paramsArr.join('&');
    };
```

**Comment by krishnaff** [comment]
@aporat Oh wow! Thanks so much. I'll see if I can hack around with this a bit.

**Comment by krishnaff** [comment]
@aporat I figured the reason the Android GET calls were not working is because I had 
`{
  method: 'GET',
  body: " "
}`
This worked absolutely fine on iOS. But on Android, they were getting interpreted as POST calls due to the presence of the empty `body` field.

Thanks for your code snippet, thats what helped me figure it out.

**Comment by kuy** [comment]
Ahh, I also struggled at `JSON.parse(response.statusText)`. In addition to this, `application/json` causes error `response.json() is not defined` error in Android. Was already reported as #2 .

@insaneinc01 Are you tackling this issue now? If not, I try to address this. Most users confuse this behaviour.

**Comment by krishnaff** [comment]
hello @kuy 
I simply changed https://github.com/aporat/cordova-plugin-fetch/blob/master/src/android/com/adobe/phonegap/fetch/FetchPlugin.java#L28
to "application/json"
That was the quickest I could make the plugin work :)

**Comment by kuy** [comment]
Thanks for pointing a line @insaneinc01 :+1: 
In Android platform, a response body is stored in `statusText` property.
I guess [this line](https://github.com/aporat/cordova-plugin-fetch/blob/master/src%2Fandroid%2Fcom%2Fadobe%2Fphonegap%2Ffetch%2FFetchPlugin.java#L104) causes the issue.

**Comment by punamdahiya** [comment]
@kuy I am getting the similar issue with JSON.parse(response.statusText). In addition to this, application/json causes error response.json() is not defined error in Android. 
Were you able to resolve the issue? Can you point or provide code snippet that worked for you?

@insaneinc01 I tried your suggestion of modifying the plugin content-type to application/json, followed by building the code and flashing on android phone but it didn't help

**Comment by punamdahiya** [comment]
I got confused with the documentation provided, https://github.com/aporat/cordova-plugin-fetch#json.

Pasting code snippet that worked for me.

```
  cordovaFetch(url +'?'+Date.now(), {
      method : 'GET',
      headers: {
        'User-Agent': 'CordovaFetch 1.0.0',
        "Accept": "application/json",
        "Content-Type": "application/json"
      },
    }).then(function (response) {
      const responseJSON = JSON.parse(response.statusText);
      console.log('statustext');
      console.log(response.status);
      console.log(responseJSON['last-modified']);
  }).catch(function(ex) {
    console.log('failed', ex)
  });
```

**Comment by krishnaff** [comment]
@punamdahiya hello, 
If the GET method call is failing on android, then please try removing the `body` parameter completely. 
I started by 
`{method: "GET", body: " ", headers: { "Accept": "application/json", "Content-Type": "application/json" }`
On android, once `body` is passed (even if its empty), its automatically going through as a POST call and hence the error.

**Comment by ehaab** [comment]
@punamdahiya can we change the get method to post method to make post json request ? Furtheremore, can you explain the steps to utilize your code for json post request on index.html on click of button.(on android)Thanks in advance.
