### ISSUE TITLE
response.json is not a function

### ISSUE THREAD

**Issue by ghost** [aporat/cordova-plugin-fetch#2]
Hi, 

I get the following error on IOS using this plugin:
TypeError: response.json is not a function. (In 'response.json()', 'response.json' is undefined)

``` javascript
    const url = API_URL + '/version';
    fetch(url)
      .then((response) => { response.json(); } )
      .then((jsonResponse) => {
        _onGetRemoteVersionSuccess(jsonResponse);
      })
      .catch((error) => {
        _onGetRemoteVersionError(error);
      });
```

Can you help me with this please ?

**Comment by krishnaff** [comment]
Same issue. `response.json() is not defined`. Anyone know a fix for this please? 

**UPDATE**: 
It doesn't work if the response is malformed, which was the problem in my case. Hence the `response.json() is not defined` error.
